### ISSUE TITLE
Signature representation.

### ISSUE THREAD

**Issue by mikewest** [WICG/signature-based-sri#16]
In https://github.com/WICG/proposals/issues/175#issuecomment-2400997796, @LPardue suggested that we rely upon HTTP Message Signatures (https://www.rfc-editor.org/rfc/rfc9421.html) rather than inventing a new header, which sounds like a wonderful idea indeed. That would look something like the following:

1.  HTML indicates the expected key:
    
    ```html
    <script src="https://my.cdn/script.js"
            crossorigin="anonymous"
            integrity="ed25519-[base64-encoded-public-key]"></script>
    ```

2.  The request/response would look like:

    ```http
    GET /script.js HTTP/1.1
    Host: my.cdn
    ```
    
    ```http
    HTTP/1.1 200 OK
    Identity-Digest: sha-256=[Structured Field Byte Sequence aka :[base64 of computed digest]:]
    Signature-Input: sig1=("identity-digest" ;created=1618884475;keyid="ed25519-[base64-encoded-public-key]"
    Signature: sig1=[Structured Field Byte Sequence aka :[base64 of computed signature value basd on signature-input]:];
    ```

I'm not interested in inventing something new here if we don't have to, so I'm happy to rely on the mechanism described here. It's pretty verbose (I'll dig through the spec to figure out which parts are required/optional, but I guess that's more or less the minimal set?), but would do what we need it to.

That said, I'm a little confused about the differences between `Repr-Digest` on the one hand, and the proposed `Identity-Digest` on the other. SRI currently operates over the bytes that remain _after_ the content is decoded per its `content-encoding`. @annevk to keep me honest on this, but that's my recollection and read of the current flow in Fetch (we [handle content codings](https://fetch.spec.whatwg.org/#handle-content-codings) in HTTP-network Fetch, and pass those bytes back down to [perform the SRI check](https://fetch.spec.whatwg.org/#cross-origin-resource-policy-header:~:text=If%20bytes%20do%20not%20match%20request%E2%80%99s%20integrity%20metadata%2C%20then%20run%20processBodyError%20and%20abort%20these%20steps.) at the bottom of Main Fetch). Does one of the headers described here represent those decoded bytes?

**Comment by mikewest** [comment]
(This would also address @ddworken's request for some kind of `Integrity-Public-Key` header, insofar as it seems like that's what `Signature-Input` contains.)

**Comment by annevk** [comment]
That's correct. And browsers would have a hard(er) time implementing checks before content codings are handled.

**Comment by mikewest** [comment]
Reading more carefully, it looks like both `Content-Digest` and `Repr-Digest` would indeed represent a digest over the encoded content, and `Identity-Digest` is what we're looking for (https://www.ietf.org/archive/id/draft-pardue-http-identity-digest-01.html#section-1-2). That said, I find the examples in Appendix A and B of RFC somewhat difficult to parse for this question specifically, but I think https://datatracker.ietf.org/doc/html/rfc9530#appendix-B.4 demonstrates the discrepancy?

In any event, if the description of the headers above matches your understanding, @LPardue, then I'd like to help you get `draft-pardue-http-identity-digest` over the line. :)

**Comment by ddworken** [comment]
> (This would also address @ddworken's request for some kind of `Integrity-Public-Key` header, insofar as it seems like that's what `Signature-Input` contains.)

For reference, see #21 for a separate issue to discuss the need for this.

**Comment by mikewest** [comment]
I took a pass at shifting the proposal over to the mechanism proposed here. @LPardue (and anyone else who's interested!), would you mind skimming https://wicg.github.io/signature-based-sri/#validation and suggesting any improvements that occur to you?

**Comment by mikewest** [comment]
Closing this out. For the moment, the approach in https://wicg.github.io/signature-based-sri/#validation seems like a reasonable way to approach this. There's likely followup work, but we can address it in more specific bugs.
