### ISSUE TITLE
Public key discoverability

### ISSUE THREAD

**Issue by ddworken** [WICG/signature-based-sri#22]
On https://github.com/WICG/proposals/issues/175 @igrigorik [posted](https://github.com/WICG/proposals/issues/175#issuecomment-2399889287):

> 2. "Do we need a mechanism (another header?) allowing the server to specify the public key used to sign the resource"
>    
>    * I would really like to see this. Could we park this under `.well-known` or something similar? I would love to avoid having to negotiate this problem vendor by vendor and have a well defined mechanism.

**Comment by ddworken** [comment]
@mikewest [replied](https://github.com/WICG/proposals/issues/175#issuecomment-2399965277):

> * `.well-known`: We could certainly spell out a way to allow developers to specify a key they plan to use. That might complicate the substitution story (in which @ddworken suggested folks could use distinct keys per resource), but no reason we couldn't make discovery more available as an option. That said, I don't think it would have the same effect as a key delivered with the resource, at least insofar as we wouldn't either be able to error out early in cases of key-mismatch, or do the client-side checks suggested in https://mikewest.github.io/signature-based-sri/#issue-e791903e without pulling that well-known file down at some point. That introduces caching questions and/or perf impact that I think we'd probably like to avoid.

**Comment by ddworken** [comment]
And then I [replied](https://github.com/WICG/proposals/issues/175#issuecomment-2400846610):

> re: `.well-known`: +1 to Mike's comment that I don't think a `.well-known` file would work well here since I expect we'll want to support per-library keys. For example, Google Analytics and Google Ads are two different JS libraries with different build processes, and I expect we may want to sign them with different keys. 
>
> I'm wondering: If we did something similar to Mike's suggestion of supporting an `Integrity-Public-Key: [base64 encoded pub key]` response header, does that actually need any browser-level support? It seems like that would essentially just be a response header that would be used to self-document that signature-based SRI is supported so that developers can manually add it to their scripts. At which point, I'm not sure the browser needs to do anything here other than maybe just having the spec recommend this as a best practice for developer UX. WDYT?

**Comment by mikewest** [comment]
To carry over from the other conversation: if we run with #16, we'd get the `Signature-Input` field for a response-by-response assertion of the key used for "free".

**Comment by igrigorik** [comment]
Agree, proposal in #16 addresses my earlier ask: script provider can start emitting `Signature` + `Signature-Input`, site embedding the resource can observe those, and opt-in to enforcing validation by replicating signature into script's integrity attribute.

**Comment by mikewest** [comment]
Added some text to this effect in https://wicg.github.io/signature-based-sri/#deployment-key-discovery.
