### ISSUE TITLE
With reporting this exposes more information

### ISSUE THREAD

**Issue by annevk** [WICG/signature-based-sri#26]
Although CORS is required, a server could additionally require the new Signature-Based-SRI request header. At which point the reporting would allow you to differentiate between failed SRI and a network error. Which is probably okay, but it doesn't seem ideal.

**Comment by ddworken** [comment]
If I understand correctly, the risk here is that a server might:

1. Support signature-based SRI
2. Inspect the `Accept-Signature` request header and only enable CORS for requests that set `Accept-Signature` 

A server might do this to support signature-based SRI without allowing full legibility of their resource. [Subresource-reporting](https://github.com/yoavweiss/subresource-reporting) would then allow an attacker to get the hash of the JS, which would represent a slight increase in information exposure compared to the server's goal. 

From thinking about this a bit more, I think this might actually be an issue inherent to subresource-reporting (and not actually unique to signature-based-SRI). The same risk would exist if 2) above was replaced with the server only enabling CORS for requests with `Sec-Fetch-Dest: script`. 

I think this represents an interesting corner of the web platform where servers could be enabling CORS only for certain types of requests, and the web platform might be treating this as enabling other types of legibility. IMO the question to ask is whether the harm of exposing hashes in this (somewhat obscure case) is a significant risk, or is it just violating an assumption that a server is making that the web platform has not promised to keep. 

My personal inclination is that protecting a response that sets CORS headers isn't something the web platform tries to do. But I am curious for other people's opinions here.

**Comment by annevk** [comment]
> The same risk would exist if 2) above was replaced with the server only enabling CORS for requests with Sec-Fetch-Dest: script.

I don't think that's true. You can determine through load/error events on the `script` element whether there was a network error or not. And you can determine that separately from including the integrity metadata as the server is not aware as to whether you included integrity metadata or not.

**Comment by annevk** [comment]
I overlooked that we only end up exposing the public key and not a hash of the response. I agree that makes this even less of an issue than I initially thought. Thanks for indulging me!

**Comment by mikewest** [comment]
I added a note to #21 to ensure that we think through this concern if we end up adding support for `Accept-Signature` (or some variant thereof). I'll close this out in the meantime, though. Thanks!
