### ISSUE TITLE
Monitoring SRI Errors

### ISSUE THREAD

**Issue by ddworken** [WICG/signature-based-sri#28]
Many other web security features support report-only modes that can be used to test whether deploying a change is safe. It seems like this may be a useful capability for signature-based SRI (and maybe, for SRI in general?). It seems like there are a number of potential directions this could go:

1. A feature that allows a page to receive notifications about any SRI violations on that page (e.g. `https://example.com` would set a `SRI-Reporting: ...` response header)
2. A feature that allows a JS library to receive notifications about any SRI violations when it is included (e.g. `https://example-3p.com/lib.js` would set a `SRI-Reporting: ...` header and receive reports if `example.com` included it)
3. A feature that allows either a page or a JS library to run SRI in report-only mode (so checking for errors, but not blocking execution). One could imagine pairing this with #27  to allow a JS library to opt-in to server-initiated report-only integrity checks. 

These do all seem like potentially useful capabilities, so I'm curious if others have thoughts on how important each of these capabilities are.

**Comment by ddworken** [comment]
My personal assessment is that:

* Option 1 seems interesting, but I don't see a large need for it from a Google perspective. Though if other folks see this as useful (e.g. @yoavweiss?) that would be useful feedback. 
* Option 2 seems potentially useful from a deployment perspective. But it is worth noting that in theory #21 makes this less useful since if a backend knows the expected public key, they can always just re-verify their own signature to ensure it validates. The only thing Option 2 would guard against is implementation bugs or MITM proxies. This makes me thing that option 2 is probably a nice-to-have, but not necessary. 
* Option 3 also seems potentially useful from a deployment perspective. Though I think the above point applies equally well (especially if we have #27 and can disable server-initiated checks). 

So my personal opinion is that all of these ideas seem like potential future improvements, but probably not necessary for the MVP.

**Comment by yoavweiss** [comment]
Well, as [discussed](https://github.com/w3c/webappsec-csp/pull/693#issuecomment-2507772330) on CSP hash reporting, I do think that SRI reporting is a useful thing.

I think it's especially important now that we have SRI for ES modules that is based on import maps. Before that, you could kinda emulate SRI reporting by catching error events on scripts and report their integrity attributes. But you can't do that for imported modules.

A separate `SRI-reporting` header kinda makes sense to me, but I've given no thought as to what that would mean for signature-based SRI. It's similarly unclear to me what would a reporting-only SRI mode look like, and if that's a necessity. I'll try to gather use-cases internally.

**Comment by ddworken** [comment]
Yeah, a separate `SRI-reporting` header seems reasonable to me. We could also imagine supporting this header on both:

1. HTML responses: Where it would report on integrity errors from that page including JS subresources
2.  JS responses: Where it would report on integrity errors when that JS subresource 

Though when thinking about it, option 2 seems like it might have expose some new cross-origin data by allowing a JS resource to know what hash the page has pinned it to. This may be acceptable, but we'd want to think this through carefully.

**Comment by mikewest** [comment]
I think some sort of reporting scheme is reasonable to design, but I'd suggest doing so in a way decoupled from this specific signature-based proposal. Presumably integrity failures would be handled in the same way for both hash- and signature-based integrity schemes. Moving this conversation back to w3c/webappsec-subresource-integrity might make sense (as you'll need to deal with feedback like @annevk's suggestions in https://github.com/w3c/webappsec-subresource-integrity/pull/122 one way or the other).

**Comment by ddworken** [comment]
Thanks all! I agree with everything that has been said here, so let's close this and move any future discussion to w3c/webappsec-subresource-integrity/issues/20.
