### ISSUE TITLE
The explainer should live at only 1 url.

### ISSUE THREAD

**Issue by jyasskin** [WICG/signature-based-sri#6]
I think https://github.com/w3c/webappsec-subresource-integrity/blob/master/signature-based-restrictions-explainer.markdown should redirect here.

**Comment by devd** [comment]
agreed. Do you know how to set this up in Github?

**Comment by devd** [comment]
(I mean .. I can delete and say "this has moved" but if there is a way to redirect, that would be great)

**Comment by jyasskin** [comment]
I don't know how to do an actual redirect, sorry.

**Comment by mikewest** [comment]
https://github.com/w3c/webappsec-subresource-integrity/pull/127 should close this.
